import type { Metadata } from "next";
import "./globals.css";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Lu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#D7D7D7] overflow-x-hidden">
      <head>
        <link
          rel="icon"
          href="/assets/icon.svg"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="preload"
          href="/assets/blacksand.jpg"
          as="image"
          type="image/jpeg"
          media="(min-width: 0)"
        />
      </head>
      <body className={`${openSans.className} antialiased`}>{children}</body>
    </html>
  );
}
